### ISSUE TITLE
Documentation Updates - Setup

### ISSUE THREAD

**Issue by ahoefling** [nvisionative/nvQuickTheme#13]
This is my first time using this tool and I love how well it is documented to get everything off and running. I noticed something that could be improved in the docs and want to see if it is something that has been thought of before.

On the wiki page [Installation](https://github.com/nvisionative/nvQuickTheme/wiki/Installation) the docs site running the project inside a DNN instance for ease of use vs having it be outside of DNN and running the package commands.

I was thinking we could recommend a hybrid solution where we can enable the windows 10 symlink so you can have the source code outside of your DNN instance but have the DNN website reference the project.

This is a practice I started doing recently for DNN module development. If this all makes sense I can go ahead and submit a PR for the wiki docs so that it can be suggested.

Here is a screenshot of the commands I used to get this working (note this will **not** work in powershell)

![image](https://user-images.githubusercontent.com/17751436/38038710-9a92c946-3279-11e8-8bd8-d7c2b2157742.png)

**Comment by bdukes** [comment]
The equivalent PowerShell is `New-Symlink -LiteralPath SimpleBlog -Target 'D:\Hoefling Software\SimpleBlog'`

**Comment by ahoefling** [comment]
@bdukes thanks, I figured you could do it but just didn't know how

**Comment by nvisionative** [comment]
@ahoefling and @bdukes - Thanks - this is a great recommendation!  We'll be happy to update the documentation.  There is no way (that I am aware of) to make a PR for the GitHub Wiki, but let me know if you know of a way.  Otherwise, just post your recommended changes here and we'll update.  That said, we would like to shift documentation to a some tool that does allow PRs for docs.  Do you have any recommendations?

**Comment by bdukes** [comment]
One option for docs is GitHub pages, which can use either a branch in the repo or a `docs/` folder in the repo, and it'll render markdown at https://nvisionative.github.io/nvQuickTheme

**Comment by nvisionative** [comment]
Thanks @bdukes

**Comment by Tychodewaard** [comment]
Hi @nvisionative 
As I didn't discover yet how to make a pull request on a wiki page, I made some annotations on my forked repo:
https://github.com/Tychodewaard/nvQuickTheme/wiki/Changing-button-style
https://github.com/Tychodewaard/nvQuickTheme/wiki/Changing-logo-size
https://github.com/Tychodewaard/nvQuickTheme/wiki/Changing-the-font
https://github.com/Tychodewaard/nvQuickTheme/wiki/Language-selector

It's work in progress but you may find it useful :-)
It's actually me writing pointers down in order to be quicker next time.

**Comment by nvisionative** [comment]
Thank you to everyone for your desire to make the docs better.  We are working to implement GitHub Pages ASAP.  Then we'll be able to process PRs on the /docs folder.

**Comment by nvisionative** [comment]
@ahoefling @bdukes @Tychodewaard we are proud to announce the new nvQuickTheme docs (using GitHub Pages) is now live.  The source for the site is located in the */docs* folder of this repo.  We will be converting markdown files to HTML eventually, but we wanted to go ahead and get the initial version published and fully functional.  Now PRs can be made to update the documentation - woo hoo!  I would recommend we create an issue for each recommended change above.  Then PRs can be made against each issue.  Can you each take a moment to create an issue for each recommendation?  And if you are comfortable, please feel free to submit a PR as well.  Otherwise, we will put it in our queue.

**Comment by nvisionative** [comment]
@Tychodewaard - I am going to use your notes for making a few short how-to videos in the new **nvQuickTheme Video Series**.  These will accompany so new how-to articles on the [new documentation site](https://nvisionative.github.io/nvQuickTheme/).

@ahoefling and @bdukes - I have created #101 to discuss the use of symbolic links during development.  

I am going to go ahead and close this issue.  Thanks again for the dialog!
