### ISSUE TITLE
Bootstrap 4 Jumbotron text color is hard to read

### ISSUE THREAD

**Issue by ahoefling** [nvisionative/nvQuickTheme#134]
## Describe the bug
When using the jumbotron from bootstrap 4 the default css framework for this theme, it does not render correctly in the banner area. The jumbotron is a light gray with the font color being white. 

We should update the font colors for jumbotron to make this work out of the box.

## To Reproduce
1. Deploy theme to dnn website
2. Create html module on the banner area
3. implement a basic jumbotron or using the example from the docs

## Expected behavior
I would expect the font color to be black when using the jumbotron

## Screenshots
![image](https://user-images.githubusercontent.com/17751436/51413650-9ba8d980-1b3d-11e9-9eac-4251686a27d6.png)

**Comment by nvisionative** [comment]
@ahoefling this is more of a custom theme implementation issue rather than an nvQuickTheme issue.  The base theme does not utilize a jumbotron.  Therefore styling has not been implemented to handle such.  

That said, there are multiple ways to handle this in your own custom theme.  The easiest way is to utilize the built-in classes for `bg-primary`, `bg-secondary`, `bg-tertiary`, etc. along with `jumbotron`.  That way, you can control the background color so that white text works.  

Out-of-the-box, the white text color is being controlled by styling for that specific content pane.  Therefore, if you want to change the text color explicitly, you can simply [change that here](https://github.com/nvisionative/nvQuickTheme/blob/master/src/scss/sections/_bannerpane.scss).

Another option is to just use the built-in Bootstrap text color classes of `text-primary`, `text-secondary`, `text-dark`, etc.

This looks like it may make an excellent new how-to video for our series, so I'll add this one to the [list here](https://github.com/nvisionative/nvQuickTheme/issues/104).
