### ISSUE TITLE
CSS Priority

### ISSUE THREAD

**Issue by dougcsicam** [nvisionative/nvQuickTheme#139]
## Please summarize your question in one sentence
The priority for CSS in the default nvQuickTheme starts at 100. It all works fine when I turn minification on in DNN until I use the Easydnnrotator module, than everything goes completely wacky. When I start them at a priority of10 things come under control but the font sizes seem to be coming from bootstrap not the css in Easydnnrotator. What should I be expecting.

**Comment by nvisionative** [comment]
@dougcsicam you may want to familiarize yourself with the **RELATIVE ORDER** section on the [DNN Wiki post here](https://www.dnnsoftware.com/wiki/client-resource-management-api).  This will help you understand how priorities are handled via DNN's Client Resource Management.  

We are going to close this issue for now since it isn't really an nvQuickTheme specific issue.  It is up to the theme developer to take into account any third-party extension considerations.  Also, you may want to reach our to EasyDNNsolutions support to understand how EDNrotator works in this regards.  Their support is fantastic!  Then you can adjust your theme accordingly.

Also, I'll add, some modules don't handle enabling Client Resource Management too well, though we have never had any problems with EDNsolutions extensions.  :)
