### ISSUE TITLE
Upgrade existing nvQuickTheme project

### ISSUE THREAD

**Issue by skrantzman** [nvisionative/nvQuickTheme#221]
## Please summarize your question in one sentence
How to upgrade an existing nvQuickTheme to a newer version of nvQuickTheme

## Give a more extended description
First I want to thank you for making nvQuickTheme available as an open source project, as this is a great DNN theme development tool.

So I started designing my first DNN theme using nvQuickTheme v2.1.0.  I would like to upgrade the project to utilize some of the new features in v2.2..0.  I am sorry if this has been covered in the past, but I can't find any info on how to upgrade an existing theme to a newer version of nvQuickTheme.  Could you please point me in the right direction?

**Comment by david-poindexter** [comment]
Thank you for the kind words @skrantzman - it is our pleasure to offer this open-source project to the DNN Community!

To "upgrade" a project to new nvQuickTheme version base is a pretty simple comparison and merge process.  We typically "cherry pick" the things we want/need based on a comparison of our old project with a new clone of the current nvQuickTheme using a tool such as WinMerge.  Our focus is more on the tooling updates rather than the actually custom theme implementation.  I hope this helps.

Enjoy nvQuickTheme!

**Comment by skrantzman** [comment]
David,

Thank you for the quick response.  I thought that might be the case, but was hoping there might be a tidier solution I was unaware of.

Steve

**Comment by david-poindexter** [comment]
Yeah, every "upgrade" is really dependent on the unique custom theme implementation, the version from which it was created, and the version to which of nvQuickTheme it is being upgraded to.  There really is no "standard" way to handle this.  We have tried to go down that path and found it to be a slippery slope.  That said, once you get accustomed to the process, it really is quite quick.  It typically takes us no more than 20 or 30 minutes to to do this.  Many times it is like 10-15 minutes.  😀
