### ISSUE TITLE
Strange Text Alignment issue in BannerPane, ContentPane, and SinglePaneOne

### ISSUE THREAD

**Issue by skrantzman** [nvisionative/nvQuickTheme#222]
## Please summarize your question in one sentence
What is the benefit of the "text-center" class in the ContentPane vs just using the alignment features in the built-in html editor, and where is text-center defined?

## Give a more extended description
If you place a Html module in the ContentPane (as well as BannerPane and SinglePaneOne), strange alignment behavior arises when trying to align text. Using the built-in html editor's alignment feature, you can center align, justify, and right align text.  If you change the alignment in the editor to left align, the result is center aligned text.  Removing the text-center class from these panes does allow you to align text anyway you want to, via the htlm editor, including left aligned.

My first thought is why would you define the text alignment in the ascx file, as this prevents the average Page Editor from controling alignment as they see fit, My second thought was that you must have had a good reason by doing just that.  If you set text alignment in the html editor to left align, and then inspect the text, you will see that text-align: left is being overridden by "center !important"  from the text-center class in the _breakpoints.scss file on line 61.  Yet there is nothing in the file that has anything to do with text-align or text-center. I searched the entire project but am unable to find out where the text-center class is defined.

So my questions are:

- Where is the text-center class defined?
- What is the purpose of this class (why use it instead of the html editor's text align feature?)
- When using the html editor's align feature why is align left the only alignment overridden by the text-center class?

## Steps to reproduce (if needed)

1. Clean install of nvQuicktheme 2.1, or 2.2 or possibly 2.0
2. Compile, build and view theme in browser
3. Add html module to ContentPane and add text.
4. Change alignment of text using the built-in html editor to left aligned.
5. View results on page - text is still center aligned.

**Comment by tksheppard** [comment]
@skrantzman 

1. The text-center class is utility class provided by the Bootstrap Framework and is defined within the Bootstrap SCSS, which is handled by our build process.
2. The purpose of this class is to provide a quick way to center text within an element by declaring a class. Since the removal of the `<center>` tag in HTML5, CSS has been the correct way to align text to the center.
3. To understand this, is to understand good methodology behind CSS, it also will help you understand how CSS is read by the browser. CSS will be handled with the following order:
    1. Inline Style - Styles declared in the element `<div style="text-align:center">`
    2. Embedded Style - Styles declared in the page `<style>.text-center { text-align: center }</style>
    3. External Style - Styles declared in an external CSS file '<link rel="stylesheet" href="style.min.css">` Best practices generally limit styles to External Stylesheets.

When you use the WYSIWYG HTML editor in DNN to style text, it is adding the CSS via Inline Styling. So now you may ask, "You just said Inline styles win over everything else. What gives?" This is where we learn about a useful/crippling tag `!important`. This is a special tag added to any CSS definition that makes it "win" against any other rule. Since your inline style doesn't have the `!important` tag, it loses to the Bootstrap class. Bootstrap adds the `!important` tag onto these class definitions because they are typically used in individual situations, much like inline styling. We want this class to win against any inherited properties, and thus `!important` is used to make sure that happens. Once 2 or more classes have the `!important` tag, the hierarchy I originally outlined comes into play again. So if you added `<div style="text-align:left !important">`, your style would win vs the Bootstrap external CSS file. 

All that being said, I recommend sticking to best practices and abandon any use of WYSIWYG text editors that add inline styling, and instead edit the template. The `default.ascx` file is the main template, and you can easily add/remove classes on the Bannerpane or any DNN pane, add/remove panes, and completely change the template. nvQuickTheme is really more about the toolset provided, than the basic theme it comes with. With a proper build process, it's easy to keep your theme project organized, packaged, and kept up.

As a side note, I don't recommend using or relying on the `!important` tag. It's too easy to use as a crutch instead of properly writing good CSS. The tag has its place, and I believe Bootstrap uses it well. But generally you should stay away from using it.

**Comment by skrantzman** [comment]
@tksheppard,

I am very verse in CSS and do understand the hierarchical nature of the different styles as well as the controversy around the use of !important (a very slippery slope once you start using it.)  For some reason I was under the impression that text-center was a Bootstrap 2-3 class, and was deprecated in Bootstrap 4 in favor of other class implementations, but I see clearly now that I was wrong in that assumption.

"_**All that being said, I recommend sticking to best practices and abandon any use of WYSIWYG text editor styling buttons that add inline styling, and instead edit the template and add good CSS classes.**_"  

I guess that this is the part that really confuses me. I would tend to agree with you, if I was developing this site for myself and maintaining it.  As as developer, it isn't a problem for me to edit the default.ascx page or any other file type for that matter on a DNN site. However isn't one of the main purpose of a content management system like DNN, to give those that have no knowledge of html and css (like many of my clients) the ability to define how they want to display content on a page using the WYSIWYG editor or other module type? 

I also find it was strange that the Bootstrap text-center class is only overriding text-align: left with the use of !important, and not the the other alignments of justified and right within the default theme. The way that I understand !important, and by your own explanation above, shouldn't !important override all alignments via the WYSIWYG editor?

Don't get me wrong, I am by no means criticizing the use of the text-center class in those panes within the default.ascx file, as I think nvQuicktheme is an excellent theme development platform for DNN. I am merely trying to understand your reasoning for placing it there. By understanding that, I can determine if I can safely remove it or not. From you explanation above, I now believe that I can do just that.

Thank you!

**Comment by tksheppard** [comment]
@skrantzman 

DNN is just like you said, a content management system, and it does that very well. It should not have any control over layout and feel--that is purely the job of the theme. Where it does allow you to insert HTML modules, I see the WYSIWYG editor as a necessary evil. It makes sense that this would be in DNN core as it is the simplest of content, and it would be the least that people need and expect.  I personally would use a structured content approach if I expected a client to change things on their site, as I feel even the basic HTML module WYSIWYG editor gives the user too much power as it creates inline styles for them (overriding mine). And in my own experience, if you give the client power to change styling, they will do so to a fault. I am also a control freak, so take that for what you will. 😄 

The reason it only seems to override `text-align: left;` is probably because the editor doesn't actually add an inline style for that. It assumes the default is left, so instead it would just remove the inline styling. That's why all other alignment options would function as it's adding it to the `<p>` tag, which will be used over a parent definition, and is actually adding inline CSS.

So the reason I used text-center on the parent is because I already knew I wanted everything in that pane to be aligned to the center, plain and simple. Sorry if I bored you with CSS info you already know, we get all types here so I try to be as helpful as possible and probably end up being too verbose. 😄 

Please, please, please don't be scared to change this theme to do whatever you need. The first thing I do when I start a project is usually strip almost everything out of the default template. Granted, we use structured content so most of the HTML is shifted from the DNN template to the structured content template. But even so, I still gut the default template right off the bat.

If you have anymore questions, please send them our way! And have a great day!
