### ISSUE TITLE
gulpfile.js for Upendo project structure

### ISSUE THREAD

**Issue by ryanjagdfeld** [nvisionative/nvQuickTheme#300]
## Using Upendo's Project Structure
I've been using @UpendoVentures development project structure from the yeoman generator-upendodnn and was in need of nvQuickTheme to build into the `..\..\Website\Portals\_default\Skins\[theme]` folder.  You can see the gulp file I've made in my fork under the "upendo-project-structure" branch, [gulpfile-upendo-project-sturcture.js](https://github.com/ryanjagdfeld/nvQuickTheme/blob/upendo_project_structure/gulpfile%20upendo-project-structure.js).  I'm curious if you are interested in having the file pulled into the main project to help developers use the nvQuickTheme build process in the Upendo project structure?  

### Note
I'm the same developer that contributed a koi.connect fix a short while back.  My account is now this one and the old one (@yog-it) was converted to an organization account.

**Comment by david-poindexter** [comment]
Hi @ryanjagdfeld.  Thanks for making the connection from the usernames.  😀 

nvQuickTheme is intended to be a base system that people will want to alter for their specific project build needs.  We intend to keep this repo focused on a solid "starting point" for general use.  Feel free to create a fork for specific needs if you will find that helpful.

I'm going to go ahead and close this issue here.

**Comment by ryanjagdfeld** [comment]
Makes sense.  Thank you for the response and this awesome repo.
