### ISSUE TITLE
screenshots 

### ISSUE THREAD

**Issue by johndpope** [nvisionative/nvQuickTheme#346]
I can see a lot of effort been put in here - 
can see youtube video - 15 steps to install / configure 
website - pointing to videos.
I just don't know what the end result will be - perhaps somescreen shots of dnn where this theme is applied would go a long way.

**Comment by david-poindexter** [comment]
https://nvquicktheme.com is the base (though it may be a bit outdated version of the base).

Since **nvQuickTheme** is more of a theme workflow/build system, ultimately, the theme will look whatever way you design it to look.  We have designed and developed hundreds of websites using **nvQuickTheme** as the base.  Here are just a few sites you can see it all in action.

* https://dnncommunity.org/
* https://dnnsummit.org/
* https://nvisionative.com/
* https://www.apmr3.com/
* https://www.charlotterentalproperties.com/
* https://crazycoolcollectibles.com/
* https://dnndave.com/
* https://juanloco.com/
* https://watersheddatagroup.com/

**Comment by johndpope** [comment]
this would be helpful on front page.
