### ISSUE TITLE
What Next?

### ISSUE THREAD

**Issue by worldheadquarters** [nvisionative/nvQuickTheme#53]
## Please summarize your question in one sentence
The documentation stops short of  explaining how to use this module..  A tutorial or further explanation would be  helpful.

## Give a more extended description
I installed the module, followed the instructions to install Gulp and Yarn (don't understand what the purpose of these is).    The documentation stops short of explaining how to use this module.  A dhort example or turorial would probably be a good idea.

## Steps to reproduce (if needed)
Follow the steps in the documentation very carefully.  When there are no more steps to follow, sit staring in bewilderment at your computer screen. (you can look at the contents of the files in your newly created skin folder, but it probably won't help.)

## Other comments or remarks
If you are the developer, do not assume that everyone reading your documentation is familiar with everything that you are familiar with. (Git, Gulp, yarn, Yawn, SCSS etc.)

**Comment by tksheppard** [comment]
Hello,

Sorry the documentation wasn’t as clear as it could be and for the frustration.

I think it’s important to note that nvQuickTheme is not a module but is instead an advanced dev tool for building DNN themes.

We recently transferred our documentation to Github pages. Now anyone is welcome to make pull requests to make the documentation better. We also plan on having tutorial videos.

We do make some assumptions due to nvQuickTheme’s dependencies.

As for information on Git, Yarn, Gulp, or SCSS, here are some links to their documentation:
[https://git-scm.com/doc](https://git-scm.com/doc)
[https://yarnpkg.com/lang/en/docs/](https://yarnpkg.com/lang/en/docs/)
[https://github.com/gulpjs/gulp/blob/master/docs/README.md](https://github.com/gulpjs/gulp/blob/master/docs/README.md)
[http://sass-lang.com/documentation/file.SASS_REFERENCE.html](http://sass-lang.com/documentation/file.SASS_REFERENCE.html)
I hope this is helpful!

**Comment by worldheadquarters** [comment]
Thanks for responding.  I realize it is not a module, but wasn;t sure what else to call it.  Id love to write documentation, but pretty difficult if I have no idea what to do next.  How about a short quick non detailed outline or list of hints.
1. use SCSS to do something
2. use Gulp to do something else
3. Now use some  Yarn
4. export the skin as a module

**Comment by nvisionative** [comment]
@worldheadquarters have you see our [documentation](https://nvisionative.github.io/nvQuickTheme/)?  There you will find detailed instructions how to use nvQuickTheme.  As far as various use cases, we do indeed plan to start doing some additional documentation and videos.  These will all be available via the [documentation](https://nvisionative.github.io/nvQuickTheme/), so stay tuned and thanks so much for your interest!

**Comment by worldheadquarters** [comment]
Yes, I read and followed all the documentation that you have on line.  That;s how I got as far as I did.  As I said earlier, the documentation is incomplete.  It explains how to install nVquicktheme and it's attendances, and how to set up a local development environment for your take on theme development - Then what?  You stopped before offering any hint or procedure for actually creating a new theme.  you just have links to other applications with no explanation as to how they relate to nvQuicktheme.  The problem with giving me all those links is that i do not even know which of the other apps to start with or why.   Even a brief outline for creating a basic simple one content pane theme using your methodology would be very helpful.
Still staring at the screen in bewilderment

**Comment by nvisionative** [comment]
@worldheadquarters we want to help you.  [Our documentation](https://nvisionative.github.io/nvQuickTheme/) (not the above links on Git, Gulp, Yarn, SCSS) is thorough for explaining exactly how to use nvQuickTheme.  That's the scope of our documentation.  As stated though, we do plan to start adding some "How To..." documentation/videos.

If you are a new DNN theme development, and need to learn the basics for that, this is not really the place to start.  The minimum requirement for using nvQuickTheme is a basic knowledge of DNN theme development.  

That said, here are several videos that may help you further with nvQuickTheme:

- [Advanced Theming Webinar](https://youtu.be/lP4M4cdDD44) (A DNN Corp sponsored webinar)
- [A New Paradigm in DNN Theme Development](https://youtu.be/gFLjScoomQw) (A DNN Connect 2018 session)
