### ISSUE TITLE
Prevent missing font

### ISSUE THREAD

**Issue by Tychodewaard** [nvisionative/nvQuickTheme#60]
## Please summarize your question in one sentence
The fonts are missing.

## Give a more extended description
In order to deliver themes that customers can relate to, I rename the install zip to customerA. Which results in themes like CustomerA-default, CustomerA-leftmenu etc.
Result is that the fonts are missing cause they are looking for an nvquicktheme folder
So, somewhere in the code it seems to insist on mentioning nvquicktheme :-)

Any way around this?

**Comment by Tychodewaard** [comment]
Maybe it's something else...I now renamed the project-details.json and the nvquicktheme folder is now renamed as well. But...the fonts are still not being loaded.
- I extended the permissions so all necessary file extensions are allowed
- I even tried uploading the woff2 files directly in the folder. I can see them in the file manager but clicking on them, it gives a 404...

**Comment by tksheppard** [comment]
The folder the manifest tells DNN to unpack to is based on the project name within `project-details.json`. Whenever the project is packaged, it should automatically update those references in the manifest. If that's messing up, you can always force it with a `gulp manifest` command, but please let me know if it's screwing up. Any reference to nvquicktheme should be abolished when the manifest is updated (`package.json` being the exception).

As for the fonts not being loaded, are the font files making it into the install package? Or is it a disconnect within the CSS somewhere? Upon packaging any reference to the `dist/` directory within template files are automatically removed, because the manifest is set to unpack the contents of the dist folder into the theme's root folder within DNN. It is possible some targeting was lost somewhere.

It sounds overall like the packaging went awry, so I'd double check your `project-details.json`, make sure it's updated, as well as run the `gulp package` command, then check the install zip to make sure the font files are making it into the zip. If not, please let me know. It's possible there is some gulp funny business going on here.

**Comment by Tychodewaard** [comment]
The fonts are making it into the zip. And within the package in the dist.zip 
But after uploading into a DNN instance (either 804 or 9.1.1) the fonts are not in the expected folder.
Maybe it is woff2 specific?

**Comment by tksheppard** [comment]
It shouldn't be woff2 specific as it is setup to zip all files in the dist folder. Not specific file types, and I've never had DNN prevent font files from extracting, so this is very puzzling.

Within your `manifest.dnn` there's a few lines that read like this:
```html    
<!-- CSS, Fonts, JS, Images Folder -->
<component type="ResourceFile">
  <resourceFiles>
    <basePath>Portals\_default\Skins\{your project name}\</basePath>
    <resourceFile>
      <name>dist.zip</name>
    </resourceFile>
  </resourceFiles>
</component>
```

{your project name} should read whatever you have setup in project-details. Does this have the correct path in your `manifest.dnn` file? Thank you for your patience.

**Comment by bdukes** [comment]
When you say that the files aren't in the expected folder, are you verifying that on the file system, or through a browser.  You _do_ need to add a MIME type mapping for IIS to serve woff2 files.

**Comment by nvisionative** [comment]
@Tychodewaard - I think @bdukes may have nailed this one - thanks Brian!

**Comment by Tychodewaard** [comment]
I think you're right @bdukes ...never crossed my mind that woff2 is not available by default...

**Comment by bdukes** [comment]
@Tychodewaard I think you missed some formatting, GitHub stripped your example

**Comment by Tychodewaard** [comment]
`    <staticContent>
      <clientCache cacheControlCustom="public" cacheControlMode="UseMaxAge" cacheControlMaxAge="365.00:00:00" />
      <remove fileExtension=".woff2" />
      <mimeMap fileExtension=".woff2" mimeType="font/woff2" />
    </staticContent>`

Hope this works better :-)

**Comment by bdukes** [comment]
If yours is already in place in the `web.config`, then that seems fine.  What I have just makes sure that's all in place during the theme install.

**Comment by nvisionative** [comment]
Thanks @bdukes for the assist - we'll go ahead and close this issue.

**Comment by bdukes** [comment]
Do you think it makes sense to add that section to the ['manifest.dnn`](/blob/master/manifest.dnn) file?

**Comment by nvisionative** [comment]
@bdukes for those that have the MIME type already configured in IIS, will this manifest addition cause any issues?

**Comment by bdukes** [comment]
If the MIME type is configured at the server level (as it is on newer versions of IIS), this will override that configuration (including the the `remove` element before the `mimeMap` element ensures there's not a conflict).  If it's already defined in the site's `web.config` (which is what will happen if you configure is in the IIS management UI for the site), this will leave it as is.

**Comment by bdukes** [comment]
FYI, looks like the defaults in IIS 10 (at least on my machine) are `font/x-woff` and `application/font-woff2`

**Comment by nvisionative** [comment]
@bdukes given that, I do not see any reason why that should not be included.  Would you like to submit a PR?
